### ISSUE TITLE
Carpeta de imágenes

### ISSUE THREAD

**Issue by Santi-hr** [DavidMoto/JapanGuessr#1]
En la carpeta images sin imágenes, al actualizar crashea dando una excepción.
Si se intenta sustituir la carpeta por un acceso directo también crashea, pero sin excepción.

Recomiendo poder configurar la ruta de la carpeta por parte del usuario

**Comment by DavidMolTor** [comment]
Implementado, en un momento saco un nuevo release.

**Comment by Santi-hr** [comment]
El botón de selección de carpeta funciona, pero no carga la información en las variables, solo en el archivo de configuración.
Ahora mismo es necesario reiniciar el programa para que se aplique el cambio.

**Comment by DavidMolTor** [comment]
Cierto, no actualizaba el directorio tras guardarlo en la configuración. Ya está corregido.
