### ISSUE TITLE
Revisión v0.2

### ISSUE THREAD

**Issue by Santi-hr** [DavidMoto/JapanGuessr#3]
Apunto pequeños y variados bugs:
- [x] "Añadir GPS" colapsa si en la carpeta no hay imágenes sin GPS
- [x] Se puede pulsar el botón de "Seleccionar" si no hay posición seleccionada. Haciendo que el programa se cierre.
- [x] Si no marcas nada y le das a "Seleccionar" se usa la posición marcada en la foto anterior.
- [x] Si se pone un segundo marcador en el mapa no desaparece el anterior

**Comment by DavidMolTor** [comment]
Todos comprobados. Por ahora he corregido el de poner varios marcadores.

**Comment by DavidMolTor** [comment]
Falta por probarlo en funcionamiento pero ya no puedes seguir si no hay una ubicación seleccionada.

**Comment by DavidMolTor** [comment]
Creo que el colapso de no haber imágenes en modo GPS se ha arreglado. Ahora, según vas pasando imágenes y se retiran de la lista, cuando no hay imágenes vuelve al menú principal.
